ARG REGISTRY_PREFIX=docker.m.daocloud.io
FROM ${REGISTRY_PREFIX}/library/elasticsearch:8.11.0

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.11.0
