name: ai-skill-sharing-platform-release

services:
  backend:
    environment:
      - APP_ENV=production

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      target: prod
